suv/urls.py
from django.urls import include, path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('articles.html', article, name='article'),
    # path('cars.html', cars, name='cars'),
    path('category.html', category, name='category'),
    path('rent.html', rent, name='rent'),
    path('transaction.html', transaction, name='transaction'),
    path('review.html', review, name='review'),
    path('favorite_api', favorite_api, name='favorite_api'),
    path('favorite_car_list', favorite_car_list, name='favorite_car_list'),
    path('login.html', login_user, name='login_user'),
    path('signup.html', signup_user, name='signup_user'),
    path('logout/', logout_user, name='logout'),
    path('api/articles/', articles, name='articles'),
    path('api/likearticles/', likearticles, name='likearticles'),
]

suv_rental/urls.py
from django.contrib import admin
from django.urls import  include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('suv.urls')),
    path('index.html', include('suv.urls')),
    path('articles.html', include('suv.urls')),
    # path('cars.html', include('suv.urls')),
    path('rent.html', include('suv.urls')),
    path('category.html', include('suv.urls')),  
    path('review.html', include('suv.urls')),  
    path('transaction.html', include('suv.urls')),  
    path('', include('social_django.urls', namespace='social')),
]

suv/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import json

# Create your models here.
class Category(models.Model):
    car_type = models.TextField(max_length=1000)

class Car(models.Model):
    name = models.TextField(max_length=1000)
    username = models.TextField(max_length=1000)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    year = models.TextField(max_length=1000)
    city = models.TextField(max_length=1000)
    price = models.TextField(max_length=1000,default=0)
    description = models.TextField(max_length=1000,default="")

class FavoriteCar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

class Article(models.Model):
    title = models.TextField(max_length=1000)
    date = models.TextField(max_length=1000)
    content = models.TextField(max_length=1000)
    like = models.IntegerField(default=0)

class Review(models.Model):
    username = models.TextField(max_length=1000)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    message = models.TextField(max_length=1000)
    created_date = models.TextField(max_length=1000)
    rating = models.TextField(max_length=1000)

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.TextField(max_length=1000)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    year = models.TextField(max_length=1000)
    city = models.TextField(max_length=1000)
    date = models.TextField(max_length=1000)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileImage = models.URLField()

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

suv/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import *

CAR_TYPE = [
    ('SUV','SUV'),
    ('CUV', 'CUV'),
    ('SEDAN','SEDAN'),
]

class ArticleForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))
    date = forms.DateField(widget=forms.DateInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))

class ReviewForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))
    car = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))
    message = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))
    created_date = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))
    rating = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '100',
    }))

class TransactionForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Please enter your car name',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))
    car_type = forms.CharField(widget=forms.Select(choices=CAR_TYPE))
    year = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'From what year is it?',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))
    location = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Your location?',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))
    date = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'maxlength' : '1000',
    }))

class CarForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Please enter your car name',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))
    car_type = forms.CharField(widget=forms.Select(choices=CAR_TYPE))
    year = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'From what year is it?',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))
    location = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Your location?',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))
    price = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Price?',
        'type' : 'text',
        'maxlength' : '255',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))

    description = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Description?',
        'type' : 'text',
        'maxlength' : '1000',
        'required' : True,
        'style' : 'border-radius:20px;',
        'label' : '',
    }))

class SignUpForm(UserCreationForm):
    image = forms.URLField(required=True)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image')

suv/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import *
import datetime
import json

# Create your views here.
counter = 0
id = 999999

def index(request):
    ln = len(Article.objects.all())-1
    article = Article.objects.all().values()[ln]
    title = article['title']
    content = article['content'].split(".")[:3]
    content = " ".join(content) + "."
    response = {'title' : title , "content" : content}
    return render(request,'index.html',response)

def review(request):
    if request.method == "POST":
        req = request.POST
        form = ReviewForm(request.POST)

        new_car = Car.objects.get(name=req['car'])
        new_car.save()

        new_review = Review.objects.create(username=req['username'],car=new_car,message = req['message'],created_date = req['created_date'],rating = req['rating'])
        new_review.save()
        return redirect('/review.html')
    else:
        form = ReviewForm()
    reviews = Review.objects.all()
    car = Car.objects.all()

    response = {'reviews' : reviews, 'car' : car}
    return render(request, 'review.html', response)

def rent(request):
    if request.method == "POST":
        req = request.POST
        form = CarForm(request.POST, request.FILES)

        type_car = Category.objects.get_or_create(car_type=req['car_type'])[0]
        type_car.save()

        new_car = Car.objects.create(name=req['name'],price=req['price'],description=req['description'],category=type_car,year = req['year'],city = req['location'],username = req['owner'],car_image = req['car_image'])
        new_car.save()
        return redirect('/category.html?q=' + req['car_type'])
    else:
        form = CarForm()
    cars = Car.objects.all()
    car_type = Category.objects.all()
    response = {'cars' : cars, 'car_type' : car_type}
    return render(request,'rent.html',response)

def transaction(request):
    if request.method == "POST":
        req = request.POST
        form = TransactionForm(request.POST, request.FILES)

        type_car = Category.objects.get_or_create(car_type=req['car_type'])[0]
        type_car.save()
        new_car = Transaction.objects.create(name=req['name'],user=request.user,category=type_car,year = req['year'],city = req['location'],date=datetime.datetime.today())
        new_car.save()
        return redirect('/transaction.html')
    else:
        form = TransactionForm()
    cars = Transaction.objects.all()
    car_type = Category.objects.all()
    response = {'cars' : cars, 'car_type' : car_type}
    return render(request,'transaction.html',response)

def article(request):
    response = {'article_list':Article.objects.all(), 'articleForm':ArticleForm()}
    return render(request,'articles.html',response)

def category(request):
    #Get GET REQUEST
    req = request.GET
    all_fav = FavoriteCar.objects.all().values()
    db = []
    for i in all_fav:
        if (i['user_id'] == request.user.id):
            db.append(i['car_id'])
    
    # Handle if no query is passed
    if 'q' in req:
        response = {'title':req['q'],'car_list':[]}
    elif 'price' in req:
        response = {'title':req['price'],'car_list':[]}
    elif 'year' in req:
        response = {'title':req['year'],'car_list':[]}
    elif 'city' in req:
        response = {'title':req['city'],'car_list':[]}
    else:
        response = {'title':'No matching car found.','car_list':[]}

    #Making Car List
    car_all = list(Car.objects.all().values())
    car_list = list()

    #Set category for each cars
    for i in range(len(car_all)):
        car_all[i]['category'] = Category.objects.get(pk=car_all[i]['category_id']).car_type
    
    if 'q' in req:
        #Set category for each cars
        for i in range(len(car_all)):
            car_all[i]['category'] = Category.objects.get(pk=car_all[i]['category_id']).car_type

        # #List all cars that fit the category
        # for i in car_all:
        #     if i['category'].lower() == req['q'].lower():
        #             car_list.append(i)  
    elif 'price' in req:
        #List all cars that fit the category
        for i in car_all:
            if i['price'] <= req['price']:
                    car_list.append(i)
    elif 'year' in req:
        #List all cars that fit the category
        for i in car_all:
            if i['year'] == req['year']:
                    car_list.append(i)
    elif 'city' in req:
        #List all cars that fit the category
        for i in car_all:
            if i['city'].lower() == req['city'].lower():
                    car_list.append(i)
    else:
        pass
    

    #Making Recomended Car
    try:
        if 'q' in req:    
        #Making Recomended Car
            #List all cars that fit the category
            trans_list = set([i['name'] for i in Transaction.objects.all().values() if i['user_id'] == request.user.id])
            for i in car_all:
                car_obj = Car.objects.get(pk=i['id'])
                if (i['category'].lower() == req['q'].lower()) and (car_obj.name not in trans_list):
                    car_list.append(i)
            response = {'title':req['q'],'recomended_car':car_list[0],'car_list':car_list}
        elif 'price' in req:
            #List all cars that fit the category
            trans_list = set([i['name'] for i in Transaction.objects.all().values() if i['user_id'] == request.user.id])
            for i in car_all:
                car_obj = Car.objects.get(pk=i['id'])
                if (i['price'].lower() == req['price'].lower()) and (car_obj.name not in trans_list):
                    car_list.append(i)
            response = {'title':req['price'],'recomended_car':car_list[0],'car_list':car_list}
        elif 'year' in req:
            #List all cars that fit the category
            trans_list = set([i['name'] for i in Transaction.objects.all().values() if i['user_id'] == request.user.id])
            for i in car_all:
                car_obj = Car.objects.get(pk=i['id'])
                if (i['year'].lower() == req['year'].lower()) and (car_obj.name not in trans_list):
                    car_list.append(i)
            response = {'title':req['year'],'recomended_car':car_list[0],'car_list':car_list}
        elif 'city' in req:
            #List all cars that fit the category
            trans_list = set([i['name'] for i in Transaction.objects.all().values() if i['user_id'] == request.user.id])
            for i in car_all:
                car_obj = Car.objects.get(pk=i['id'])
                if (i['city'].lower() == req['city'].lower()) and (car_obj.name not in trans_list):
                    car_list.append(i)
            response = {'title':req['city'],'recomended_car':car_list[0],'car_list':car_list}
        else:
            pass
    except:
        response = {'title':'No matching car found yaa.','car_list':[]}

    #If there is no car, then say no matching cars
    if (not car_list):
        response = {'title':'No matching car found.','car_list':[]}
        return render(request,'category.html',response)

    response['fav_cars'] = db
    return render(request,'category.html',response)

def favorite_api(request):
    all_fav = FavoriteCar.objects.all().values()
    db = []
    for i in all_fav:
        if i['user_id'] == request.user.id:
            db.append(i['car_id'])
    if 'like' in request.POST:
        if request.POST['like'] not in db:
            tmp = FavoriteCar.objects.create(user_id=request.user.id,car_id=request.POST['like'])
            tmp.save()
    elif 'unlike' in request.POST and db:
        tmp = FavoriteCar.objects.get(user_id=request.user.id,car_id=request.POST['unlike'])
        tmp.delete()
    if 'q' in request.POST:
        return redirect('/category.html?q=' + request.POST['q'])
    else:
        return redirect('/favorite_car_list')

def favorite_car_list(request):
    all_fav = FavoriteCar.objects.all().values()
    db = []
    for i in all_fav:
        if i['user_id'] == request.user.id:
            tmp = i['car_id']
            tmp = Car.objects.get(pk=tmp)
            db.append(tmp)
    return render(request,'favorite-car.html',{'cars':db})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        user_dict = {'username':username, 'password':password}
        if user is not None:
            login(request, user)
            return redirect('/')
        
        else:
            message = {'message':'Invalid username or password'}
            return render(request, 'login.html', message)
    
    else :
        return render(request, 'login.html')

def logout_user(request):
    request.session.flush()
    logout(request)
    return redirect('/')

def signup_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.profileImage = form.cleaned_data.get('image')
            user.save()
            return redirect('/login.html')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})


@csrf_exempt
def articles(request):
    data = json.loads(request.body)
    article = Article.objects.create(
        title = data['title'],
        date = data['date'],
        content = data['content']
    )

    article_list = []

    article_list.append({
        'id' : article.id,
        'title': article.title,
        'date': article.date,
        'content': article.content,

    })
    return JsonResponse({
        'article' : article_list
    })

@csrf_exempt
def likearticles(request):

suv/templates/articles.html
{% extends 'base.html' %}
<!doctype html>
{% load static %}

<script src="{% static 'js/script.js' %}"></script> 

{% block content %}
<body style="overflow-x:hidden; background-color:#D8E7E6;">
	
	<div class="row">
		<h1 class="title text-center" style="margin-top: 30vh; width: 100%; text-align: center; font-weight: bold; color: #08154A;">A R T I C L E S</h1>
		<div class="line" style="width: 200px; height: 15px; margin: 15px auto; background-color: #40D0CE; border-radius: 15px;"></div>
	</div>
	<div class="form" id="rent">
		{% csrf_token %}
		<div class="form-group">
			<label for="title" class="expl">{{articleForm.title.label_tag}}</label>
			{{articleForm.title}}
		</div>
		<div class="form-group">
			<label for="date" class="expl">{{articleForm.date.label_tag}} (YYYY-MM-DD)</label>
			{{articleForm.date}}
		</div>
		<div class="form-group">
			<label for="name" class="expl">{{articleForm.content.label_tag}}</label>
			{{articleForm.content}}
		</div>
		<button id="submitBtn" onclick="articles()">Submit</button>
	</div>

	
	<div style="max-height: 3000px; overflow-y: scroll;" class="content">
		{% for article in article_list %}
			<div class="row articleBox">
				<h1 class="articleTitle" style="margin-left: 0;">{{ article.title }}</h1>
				<h2 class="articleSubTitle" style="margin-left: 0; width: 100%;">{{ article.date }}</h2>
				<p class="articleText" style="width: 100%;">{{ article.content }}</p>
				<br>
				<p style="margin:0;">Likes: </p>
				<p id='like{{ article.id }}' style='margin: 0; font-weight: bold;'></p>
				{% if user.is_authenticated %}
				<button class='btn' type='button' onclick="likearticles({{ article.id }})" id='likeBtn{{ article.id }}' style="padding: 0; margin-left: 7px; font-weight: bold; color:#40D0CE;">Like</button>
				{% else %}
				<button class='btn' type='button' id='likeBtn{{ article.id }}' style="padding: 0; margin-left: 7px; font-weight: bold; color:#40D0CE;"><a href="signup.html">Like</a></button>
				{% endif %}
			</div>
		{% endfor %}
	</div>
</body>
{% endblock %}
</html>

suv/templates/index.html
{% extends "base.html" %}
{% load static %}   
{% block content %} 

<div class="home">
	<div class="row one">
		<div class="col-md-8">
			<div class="greetings">
				<h1>Looking for a nice ride?<br><span>We've got you cover!</span></h1>
			</div>
			<div class="rentBtn">
				<a href="transaction.html"><button id="rent">Start Renting</button></a>
				<h1>or <a href="rent.html"><span>Rent Your Car</span></a></h1>
			</div>
		</div>
		<div class="col-md-4">
			<div class="landingpage" style="float: right;">
				<img src="/static/img/LANDINGPAGE.svg" alt="" style="float: right;">
			</div>
		</div>
	</div>
</div>

<div id="category">
	<div class="row two">
		<div class="greetings">
			<h1>C A T E G O R Y</h1>
			<div class="line"></div>
		</div>
		<div id="carouselCategory" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner">
			  <div class="carousel-item active">
				<img src="/static/img/SUV.svg" alt="...">
				<h1 class="carType"><a href="category.html?q=SUV">SUV</a></h1>
			  </div>
			  <div class="carousel-item">
				<img src="/static/img/CUV.svg" alt="...">
				<h1 class="carType"><a href="category.html?q=CUV">CUV</a></h1>
			  </div>
			  <div class="carousel-item">
				<img src="/static/img/SEDAN.svg" alt="...">
				<h1 class="carType"><a href="category.html?q=SEDAN">SEDAN</a></h1>
			  </div>
			</div>
			<a class="carousel-control-prev" href="#carouselCategory" role="button" data-slide="prev">
			  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			  <span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselCategory" role="button" data-slide="next">
			  <span class="carousel-control-next-icon" aria-hidden="true"></span>
			  <span class="sr-only">Next</span>
			</a>
		  </div>
	</div>
</div>

<div id="articles">
	<div class="row three">
		<div class="greetings">
			<h1>A R T I C L E S</h1>
			<div class="line"></div>
			<img src="/static/img/DOUBLE.svg">
		</div>
		<div class="article">
			<h1 id="title">
				{{ title }}
			</h1>
			<p id="paragraph">
				{{ content }}
			</p>
			<a href="articles.html"><button id="read">Continue Reading</button></a>
		</div>
	</div>
</div>

<div id="about">
	<div class="row four">
		<div class="col-md-6 aboutImg">
			<img src="/static/img/ABOUT.svg">
		</div>
		<div class="col-md-6 aboutText">
			<p>
				Hello there! we are the development group of this project, we make this website in order to make a platform for those who want to rent a car or want your car to be rented. We took alot of effort in making this website so we hope you have the best experience when using this website. Happy Renting!			</p>
		</div>
	</div>
</div>
{% endblock %}

suv/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            background-color: #F0FAF9;
            font: 20px/1.5 'Open Sans', sans-serif;
        }
        #logOut, #signUp {
            width: 20%;
            /* margin-left: 337px;
            margin-right: 337px; */
            margin-bottom: 5px; 

            background-image: linear-gradient(to right,#40D0CE,#1C2E7C); 
            border-radius: 50px; color: #F0FAF9; 
            box-shadow: -3px -3px 3px 0 rgba(255,255,255,0.7), 3px 3px 3px 0 rgba(0,0,0,0.2);
        }
        /* #logOut {
           margin-left: 345px;
           margin-right: 345px; 
        } */
        #logOut:hover, #signUp:hover {
            background-image: linear-gradient(to left,#40D0CE,#1C2E7C); 
            box-shadow: inset 3px 3px 3px 0 rgba(0,0,0,0.2);
        }
        label{
            font-weight: bold;
        }
        input{
            padding: 5px;
            padding-left:15px;
            width: 750px;
            background-color: #D8E7E6;
            border: none;
            font-size: 20px;
            color: #909090;
        }
        #id_username {
            margin-left: 130px;
        }
        #id_email{
            margin-left: 93px;
        }
        #id_first_name {
            margin-left: 128px;
        }
        #id_last_name {
            margin-left: 130px;
        }
        #id_password1 {
            margin-left: 135px;
        }
        #id_image {
            margin-left: 168px;
        }
        ul li {
            margin-left: 225px;
        }
        span{
            margin-left: 243px;
        }
        #desc {
            font-size: 15px; 
            color: #909090;
        }
        #logIn, #homepage {
            padding: 0; 
            padding-bottom: 3px;
            font-size: 15px; 
            font-weight: bold; 
            color: #40D0CE; 
        }
        #logIn:hover {
            text-decoration: underline;
        }
        #profile {
            margin-left: 335px;
            margin-right: 335px;
            margin-bottom: 20px;
        }
    </style>

    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spartan:400,600,700&display=swap" rel="stylesheet">

    <title>Sign Up</title>
</head>
<body>
    <div style="margin: 100px; margin-top: 0;">
        <div class="row-lg-12 mb-5" style="padding-left: 120px; padding-right:120px;">
            {% if user.is_authenticated %}
            <h1 class="title text-center" style="color: #40D0CE; font-weight: bold; margin-top: 70px; margin-bottom: 20px; font-size: 60px;" id="welcome">Welcome, {{ request.user }}!</h1>
            <img src="{{user.profile.profileImage}}" class="img-fluid align-middle" style="width: 200px; border-radius: 100px;" id="profile">
            <br>
            <div class="text-center" style="width: 100%;">
                <a href="logout/"><button type="submit" class="btn align-middle" id="logOut">Log Out</button></a>
            </div>
            <a href="/"><h1 class="text-center" id="homepage">Homepage</h1></a>
            {% else %}
            <h1 class="text-center" style="color: #40D0CE; font-weight: bold; margin-top: 70px; margin-bottom: 20px; font-size: 40px;">CREATE A NEW ACCOUNT</h1>
            <form method="post" >
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center" style="width: 100%;">
                    <a href="index.html"><button class="btn align-middle" id="signUp">SIGN UP</button></a>
                </div>
            </form>
            <h1 class="text-center" id="desc" >Already have an account? <a class="nav-link js-scroll-trigger" id="logIn" href="login.html">Log In</a></h1>
            {% endif %}
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"   integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="   crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>